#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    url: jdbc:postgresql://localhost:5432/mydb
#    driver-class-name: org.postgresql.Driver
#    username: produser
#    password: secret
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    database-platform: org.hibernate.dialect.PostgreSQLDialect